'''
Nome:Matheus Santhiago Fortonato de Souza
Data:23/05/2025
Enunciado: Faca um programa que leia um numero inteiro qualquer e msotre na tela a sua tabela.
'''

Num = int(input('Digite um numero para ver sua tabiada: '))
print('{} x {:2} = {}'.format(Num, 1, Num*1))
print('{} x {:2} = {}'.format(Num, 2, Num*2))
print('{} x {:2} = {}'.format(Num, 3, Num*3))
print('{} x {:2} = {}'.format(Num, 4, Num*4))
print('{} x {:2} = {}'.format(Num, 5, Num*5))
print('{} x {:2} = {}'.format(Num, 6, Num*6))
print('{} x {:2} = {}'.format(Num, 7, Num*7))
print('{} x {:2} = {}'.format(Num, 8, Num*8))
print('{} x {:2} = {}'.format(Num, 9, Num*9))
print('{} x {:2} = {}'.format(Num, 10, Num*10))